---
- name: install apt packages
  become: true
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - git
    - nginx

- name: add deploy private key
  copy: src=~/.ssh/raspi-deploy dest=~/.ssh/ mode=600

- name: add deploy public key
  copy: src=~/.ssh/raspi-deploy.pub dest=~/.ssh/ mode=600

- name: add ssh config
  copy: src=ssh-config.txt dest=~/.ssh/config

# www app server service
- name: clone app
  git:
    repo: https://github.com/johnelliott/raspi-livestream-box.git
    dest: "{{ app_path }}"
    version: "{{ app_version }}"
    force: true

- name: copy picast environment configuration
  copy: src=picast.env dest={{ app_path }}/.env

- name: build app
  shell: . $HOME/.nvm/nvm.sh && npm install
  args:
    chdir: "{{ app_path }}"
    executable: /bin/bash

- name: create systemd journal dir
  file: path=/var/log/journal state=directory mode=775 group=systemd-journal
  become: true

- name: add user to systemd-journal group
  user:
    name: "{{ user }}"
    groups: systemd-journal
    append: true
  become: true

- name: clear nginx sites
  become: yes
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx install
  become: yes
  file:
    dest: /etc/nginx/sites-enabled/picast.nginx.conf
    src: /home/{{ user }}/picast/picast.nginx.conf
    state: link
    owner: root

- name: nginx reload
  become: yes
  shell: /usr/sbin/nginx -s reload
  args:
    executable: /bin/bash

- name: install www
  become: yes
  file:
    dest: /etc/systemd/system/picast-www.service
    src: /home/{{ user }}/picast/picast-www.service
    state: link
    owner: root

- name: enable www
  become: yes
  systemd:
    name: picast-www
    enabled: yes
    state: started
    daemon_reload: yes
  notify: restart www
